name: random-ids
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - fastapi==0.110.0
    - uvicorn==0.27.1
    - requests==2.31.0
    - jinja2==3.1.3
    - python-multipart==0.0.9 